const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    height: "100%",
    overflow: "hidden",
    backgroundColor: "#ffffff",
  },
  upperBar: {
    position: "sticky",
    top: 0,
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    boxSizing: "border-box",
  },
  skeletonContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    padding: 2,
    width: "100%",
  },
  imageListContianer: {
    maxWidth: "600px",
  },
  imageCard: {
    transition: "all 0.2s ease-in-out",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  outfitContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px 0 10px",
    width: "90%",
    maxWidth: "600px",
    margin: "0 auto",
    overflowY: "auto",
    gap: 3,
  },
  pageTitle: {
    fontSize: "32px",
    fontWeight: "700",
    color: "#000000",
  },
  pageSubtitle: {
    fontSize: "16px",
    color: "#666666",
    textAlign: "center",
  },
  modelImageContainer: {
    width: "100%",
    aspectRatio: "1",
    borderRadius: "12px",
    backgroundColor: "#f5f5f5",
  },
  modelImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  sectionTitle: {
    fontSize: "24px",
    fontWeight: "600",
    color: "#000000",
    alignSelf: "flex-start",
  },
  itemCard: {
    display: "flex",
    alignItems: "center",
    padding: "12px",
    gap: 3,
    borderRadius: "12px",
    backgroundColor: "#FAFAFA",
    boxShadow: "none",
    border: "none",
  },
  itemThumb: {
    width: "60px",
    height: "60px",
    borderRadius: "8px",
    backgroundColor: "#f5f5f5",
    overflow: "hidden",
  },
  itemImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  itemDetails: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 1,
  },
  itemTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#000000",
  },
  itemStore: {
    fontSize: "14px",
    color: "#666666",
  },
  buyButton: {
    padding: "8px 16px",
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    border: "1.5px solid #000000",
    color: "#000000",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  itemsContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
} satisfies Record<string, React.CSSProperties>;

export default styles;
